### ISSUE TITLE
Automatic deployment to AWS infrastructure using GitHub Actions and TerraForm

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/theater-hub-client#96]
We need an automatic deployment pipeline that would deploy the solution to AWS.

* We want to use Github Actions as the CD provider.

* The CD pipeline deploys the result of the build to an AWS S3 bucket where it will be statically served 

* Frontend
    - Google Cloud API key -> /config/env/_common.js
    - URL de frontend -> /config/env/_common.js
    - URL de API -> /config/env/_common.js

**Comment by eugen** [comment]
I'll take this as well, thanks.

**Comment by RaduCStefanescu** [comment]
Hi @eugen 
This issue is in progress and assigned to you.
Let us know if we can help in any way, with any kind of information.

**Comment by RaduCStefanescu** [comment]
We reduced the scope for this issue.
The deployment is done on AWS S3 bucket.
This is handled in #112 
What needs to be done next is to have a TerraForm script that creates the S3 bucket on deployer infrastructure. This will be handled in a separate PR.
